language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  directories:
    - "~/.platformio"
    - web/node_modules

env:
  - PLATFORMIO_ENV=esp12e
  - PLATFORMIO_ENV=esp12e_160

install:
  # PlatformIO
  - pip install -U https://github.com/platformio/platformio-core/archive/develop.zip
  - platformio update
  - platformio lib install
  # install node
  - nvm install node
  - cd web && npm install && cd ..

script:
  - npm --prefix web test
  - platformio run --environment=$PLATFORMIO_ENV
  - scripts/stylecheck
  - git diff --exit-code

before_deploy:
  - scripts/before_deploy
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: YuOC7ONEg48MjhJqiO/eG3sGfklmn/KHKb3xIQgHeboFoiLxqtuNdc14IxiruA37DrrUPpaDggaZnaiJjNE/z4Bn+6XeLSG7WAeLMC6A5Ok9iMUFS/L7vIqesu9pNvD4hC/pPArqkmCCFLshVoqqiTCU6KFmKfCXGaCraC0pm1FsdLGV16Z1giauCwka/uh77YdJ/JGbO+gPPBdBxV1r2+FQy5CCoZfRyW7WiZn4NpaJJ5Mw6XloiASRlb9oFFlZDl2w1wg4NaozjX/iT8Aw7mrf1mkcIMLRvsqkN3iiny5PclggEntibAjThLRFSjBt4+MVpPPew425HICXDASNu2U/D/ePKn+fk64or6lRd1E0RLwKESLltFCfPOPcQHunXqSdIBw2YG0UnosuH1RCfphCI05ypWm0du2VIYkr+NmOy6MhIwYntmaOfRP/DTNKJvyQS7wWRhCCCXGeksp3zZIAuUhRbFjJCiGvTpOjQFUXbhp0XepYqKkPx1EglnqPkEMb1Qenpw/tVb/c1cM89UxgMwo4CCWwlAmPxeVOd/VIJ5AWxOvtAaNVpPhcUmu2UIgBj+T/BVH1HF4vb+ypqMv0Pyo6DoM/yl6Y/BbfeHFPSimUYMFnSTJ5nSkgiC89EjVPz8GHuKIZ4+DBgJTX5Qg+/6a0oHViu2tWWLTLvAo=
  file_glob: true
  file: dist/*.bin
  skip_cleanup: true
  on:
    repo: puuu/MQTT433gateway
    tags: true
